name: pp_23
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  theme_provider: ^0.6.0
  google_fonts: ^6.1.0
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8
  http: ^1.2.0
  equatable: ^2.0.5
  path_provider: ^2.1.2
  webview_flutter_android: ^3.14.0
  webview_flutter_wkwebview: ^3.10.2
  webview_flutter: ^4.4.4
  flutter_gen: ^5.4.0
  flutter_markdown: ^0.6.18+3
  flutter_svg: ^2.0.9
  in_app_review: ^2.0.8
  flutter_app_info: ^2.0.0
  shimmer: ^3.0.0
  custom_sliding_segmented_control: ^1.8.1
  fl_chart: ^0.66.1
  pull_down_button: ^0.9.3
  flutter_native_splash:
  connectivity_plus: ^5.0.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
    
flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#171C21"
  image: assets/images/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
